# Generated by Django 5.2.1 on 2026-02-15 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Posts', '0003_alter_blogs_publish_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Describe what this reading list is about', null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Make this list visible to other users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading List',
                'verbose_name_plural': 'Reading Lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_in_lists', to='Posts.blogs')),
                ('readlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='readlist.readlist')),
            ],
            options={
                'verbose_name': 'ReadListItem',
                'verbose_name_plural': 'ReadListItems',
                'ordering': ['position', '-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='readlist',
            index=models.Index(fields=['user', '-created_at'], name='readlist_re_user_id_63c9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='readlist',
            index=models.Index(fields=['slug'], name='readlist_re_slug_57f3f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readlist',
            unique_together={('user', 'title')},
        ),
        migrations.AddIndex(
            model_name='readlistitem',
            index=models.Index(fields=['readlist', 'position'], name='readlist_re_readlis_266b43_idx'),
        ),
        migrations.AddIndex(
            model_name='readlistitem',
            index=models.Index(fields=['readlist', 'is_read'], name='readlist_re_readlis_c350ec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readlistitem',
            unique_together={('readlist', 'blog')},
        ),
    ]
