# Generated by Django 5.2.1 on 2026-02-13 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='publish_status',
            field=models.CharField(choices=[('Published', 'published'), ('Draft', 'draft')], default='Published', max_length=9),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
        migrations.AddIndex(
            model_name='blogs',
            index=models.Index(fields=['slug'], name='Posts_blogs_slug_2c7563_idx'),
        ),
    ]
