# Generated by Django 5.2.1 on 2026-02-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_blogs_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterField(
            model_name='blogs',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Upload a featured image for your blog post', null=True, upload_to='blog_images/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
