# Generated by Django 5.2.1 on 2026-02-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_blogs_publish_status_alter_blogs_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='publish_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=9),
        ),
    ]
