# Generated by Django 5.2.1 on 2026-02-12 03:03

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_blogs_options_alter_blogs_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
