# Generated by Django 5.2.1 on 2026-02-14 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_alter_blogs_publish_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Describe what this reading list is about', null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('is_public', models.BooleanField(default=False, help_text='Make this list visible to other users')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading List',
                'verbose_name_plural': 'Reading Lists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='Posts_readl_user_id_170f1b_idx'), models.Index(fields=['slug'], name='Posts_readl_slug_bce9ac_idx')],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
