# Generated by Django 5.2.1 on 2026-02-15 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_alter_readlist_created_at_alter_readlist_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_in_lists', to='Posts.blogs')),
                ('readlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Posts.readlist')),
            ],
            options={
                'verbose_name': 'ReadListItem',
                'verbose_name_plural': 'ReadListItems',
                'ordering': ['position', '-added_at'],
                'indexes': [models.Index(fields=['readlist', 'position'], name='Posts_readl_readlis_4a08db_idx'), models.Index(fields=['readlist', 'is_read'], name='Posts_readl_readlis_005a60_idx')],
                'unique_together': {('readlist', 'blog')},
            },
        ),
    ]
