# Generated by Django 5.2.1 on 2026-02-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0006_readlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readlistitem',
            name='readlist',
        ),
        migrations.AlterUniqueTogether(
            name='readlistitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='readlistitem',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadList',
        ),
        migrations.DeleteModel(
            name='ReadListItem',
        ),
    ]
